
CREATE TABLE SERVICES
(
	SERVICEWEBSITE CHARACTER VARYING(30) PRIMARY KEY,
	SERVICENAME CHARACTER VARYING(30) UNIQUE  NOT NULL
);

CREATE TABLE ROLES
(
	ROLEID SERIAL PRIMARY KEY,
	ROLENAME CHARACTER VARYING(30) UNIQUE  NOT NULL
);

CREATE TABLE USERS
(
	  USERID SERIAL PRIMARY KEY,
	  FIRSTNAME CHARACTER VARYING(30),
	  LASTNAME CHARACTER VARYING(30),
	  EMAIL CHARACTER VARYING(30),
	  PASSWORD CHARACTER VARYING(30),
	  SERVICEWEBSITE CHARACTER VARYING(30),
	  AGE INTEGER,
	  ACTIVATECODE CHARACTER VARYING(100),
	  ISACTIVATE BOOLEAN,
	  ROLEID INTEGER,
	  FOREIGN KEY (SERVICEWEBSITE) REFERENCES SERVICES (SERVICEWEBSITE) ON DELETE CASCADE,
	  FOREIGN KEY (ROLEID) REFERENCES ROLES (ROLEID) ON DELETE CASCADE
);