package Models.Enums;

public enum AdvertisementNotificationType {
	
	TAKE_ADVERTISEMENT,
	REJECTED_TAKE_ADVERTISEMENT,
	ACCEPTED_TAKE_ADVERTISEMENT,
	RECEIVE_SERVICE,
	ACCEPTED_RECEIVE_SERVICE,
	REJECTED_RECEIVE_SERVICE,
	CHANGE_ORDER_STATUS_TO_INPROGRESS,
	CHANGE_ORDER_STATUS_TO_COMPLETED,
	CHANGE_REITING,
	REJECTED_CERTIFICATION,
	ACCEPTED_CERTIFICATION
}
