package Models.Enums;

public enum AdvertisementNotificationType {
	
	TAKE_ADVERTISEMENT,
	REJECTED_TAKE_ADVERTISEMENT,
	ACCEPTED_TAKE_ADVERTISEMENT,
	RECEIVE_SERVICE,
	ACCEPTED_RECEIVE_SERVICE,
	REJECTED_RECEIVE_SERVICE,
}
